### ISSUE TITLE
Recorrección Tarea 2 Pregunta 2

### ISSUE THREAD

**Issue by VicenteMerino** [VicenteMerino/IIC3253-cryptography-and-computer-security#7]
El cambio realizado fue el siguiente:

```python
...
def generar_clave(l: int):
  if l < 0:
    raise Exception("Length of the keys must be positive")
  P = generar_primo(l)
  Q = generar_primo(l)
  while P == Q:
    Q = generar_primo(l)
  N = P*Q
  Phi_N = (P - 1)*(Q - 1)
...
```

por 

```python
...
def generar_clave(l: int):
  if l < 0:
    raise Exception("Length of the keys must be positive")
  P = generar_primo(l//2+1)
  Q = generar_primo(l//2+1)
  while P == Q:
    Q = generar_primo(l//2+1)
  N = P*Q
  Phi_N = (P - 1)*(Q - 1)
...
```

Por un tema de eficiencia, usar el mismo l, si bien, bastaba, esto generaba un timeout. En clases se comentó que usar l/2 (funcion techo) era suficiente para generar una clave de largo l. En este caso usamos `l//2+1` para asegurarnos que se cumpla siempre la funcion techo y en caso de que de exacto y nos pasemos, igual tendremos "al menos" largo l.

Creo que esto debería poder aplicar para la recorrección, ya que en clases se nos dijo que tanto usando l como l/2 funcionaba para generar una llave de al menos l (sin especificar cuál deberíamos usar) y múltiples veces también se dijo que no sería la idea tratar de "pillarnos" por términos de complejidad/eficiencia, por lo cual considero que este cambio califica como un cambio menor.

**Comment by Jamidd** [comment]
Hola 
tus resultados fueron:
100%, 85% 
600TimedOut-600TimedOut-600TimedOut
Nota 6
Saludos, 
Jaime.

**Comment by VicenteMerino** [comment]
@Jamidd esto es la nota de la pregunta verdad?

**Comment by Jamidd** [comment]
Si
